.TH FAST SETUP
.SH Debian Installation

.nr step 0 1
.B
.IP \n+[step]
.B Sudo

\(-> Login as root

.EX
apt install sudo
usermod -aG sudo konrad
reboot
.EE

.B
.IP \n+[step]
.B Copy Dotfiles from Backup to ~/Dotfiles/

.B
.IP \n+[step]
.B Packages

.EX
xargs sudo apt -y install < ~/Dotfiles/packages
.EE

.B
.IP \n+[step]
.B Network

.EX
managed=true
.EE

\(-> /etc/NetworkManager/NetworkManager.conf

.B
.IP \n+[step]
.B Neovim

.nr sstep 0 1

.IP \n+[sstep]
.B Clone repository

.EX
mkdir -p .config/nvim
git clone https://github.com/neovim/neovim ~/.config/nvim/
.EE

.IP \n+[sstep]
.B Build

.EX
cd .config/nvim/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
.EE

\(-> init.lua \(-> ~/.config/nvim/init.lua

.IP \n+[sstep]
.B Folder Structure

.EX
mkdir -p ~/.config/nvim/pack/lspconfig/start/
mkdir -p ~/.config/nvim/pack/LuaSnip/start/
mkdir -p ~/.config/nvim/pack/cmp/start/
mkdir -p ~/.config/nvim/pack/cmp_luasnip/start/
.EE

.IP \n+[sstep]
.B Plugins

.EX
git clone https://github.com/neovim/nvim-lspconfig  ~/.config/nvim/pack/lspconfig/start/
git clone https://github.com/L3MON4D3/LuaSnip.git ~/.config/nvim/pack/LuaSnip/start/
git clone https://github.com/hrsh7th/cmp-buffer.git ~/.config/nvim/pack/cmp/start/
git clone https://github.com/hrsh7th/cmp-cmdline.git ~/.config/nvim/pack/cmp/start/
git clone https://github.com/hrsh7th/cmp-nvim-lsp.git ~/.config/nvim/pack/cmp/start/
git clone https://github.com/hrsh7th/cmp-path.git ~/.config/nvim/pack/cmp/start/
git clone https://github.com/hrsh7th/nvim-cmp.git ~/.config/nvim/pack/cmp/start/
git clone https://github.com/saadparwaiz1/cmp_luasnip.git ~/.config/nvim/pack/cmp_luasnip/start/
.EE

.B
.IP \n+[step]
.B Zsh

.nr sstep 0 1

.IP \n+[sstep]
.B Default Shell

.EX
chsh -s /usr/bin/zsh
.EE

.B
.IP \n+[step]
.B Suckless
.nr sstep 0 1

.IP \n+[sstep]
.B Clone Repository

.EX
mkdir .config/suckless
git clone https://git.suckless.org/dmenu ~/.config/suckless
git clone https://git.suckless.org/dwm ~/.config/suckless
git clone https://git.suckless.org/slock ~/.config/suckless
.EE

.IP \n+[sstep]
.B Dwm

.EX
cp ~/Dotfiles/dwm.c ~/.config/suckless/dwm/
cp ~/Dotfiles/config.h ~/.config/suckless/dwm/
cp -r ~/Dotfiles/scripts/ ~/.config/suckless/dwm/
.EE

\(-> sudo make install [ALL]

.B
.IP \n+[step]
.B Touchpad

.EX
sudo cp ~/Dotfiles/40-libinput.conf /etc/X11/xorg.conf.d/40-libinput.conf
.EE

.B
.IP \n+[step]
.B Firewall

.EX
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow DNS
sudo ufw allow CUPS
.EE

.B
.IP \n+[step]
.B GRUB

.EX
set GRUB_TIMEOUT=0
.EE

\(-> /etc/default/grub

.EX
sudo update-grub2
.EE

.B
.IP \n+[step]
.B Disable Applications

.EX
systemctl disable bluetooth.service
systemctl disable NetworkManager-wait-online.service
.EE

.B
.IP \n+[step]
.B Tutanota

.EX
sudo wget https://app.tuta.com/desktop/tutanota-desktop-linux.AppImage -O /usr/bin/tutanota.AppImage
sudo chmod +x /usr/bin/tutanota.AppImage
.EE
