.TH SETUP MANUAL
.SH Debian Installation

.nr step 0 1
.B
.IP \n+[step]
.B Sudo and User

\(-> Login as root

.EX
su

apt install sudo

sudo usermod -aG sudo konrad

reboot
.EE

.B
.IP \n+[step]
.B Packages

.EX
\[bu] make          \[bu] libxrandr-dev         \[bu] xorg              \[bu] libfontconfig-dev

\[bu] xinit         \[bu] gcc                   \[bu] libx11-dev        \[bu] network-manager

\[bu] libxft-dev    \[bu] libxinerama-dev       \[bu] libfreetype-dev   \[bu] git-core 

\[bu] pavucontrol   \[bu] pulseaudio            \[bu] pulsemixer        \[bu] libssl-dev

\[bu] farbfeld      \[bu] xinput                \[bu] ntp               \[bu] ufw

\[bu] xss-lock      \[bu] unzip                 \[bu] gparted           \[bu] zlib1g-dev            

\[bu] exfatprogs    \[bu] cron                  \[bu] dosfstools        \[bu] system-config-printer

\[bu] mtools        \[bu] libavcodec-extra      \[bu] brightnessctl     \[bu] openprinting-ppds

\[bu] cups          \[bu] printer-driver-all    \[bu] cups-filters      \[bu] foomatic-db-engine

\[bu] hp-ppd        \[bu] sane                  \[bu] cups-pdf          \[bu] printer-driver-cups-pdf

\[bu] sane-utils    \[bu] sane-airscan          \[bu] libsane           \[bu] simple-scan

\[bu] libsane1      \[bu] libsane-hpaio         \[bu] hplip             \[bu] printer-driver-hpcups

\[bu] libbz2-dev    \[bu] libreadline-dev       \[bu] libsqlite3-dev    \[bu] build-essential

\[bu] tk-dev        \[bu] liblzma-dev           \[bu] xz-utils          \[bu] libncursesw5-dev

\[bu] libffi-dev    \[bu] libxml2-dev           \[bu] libxmlsec1-dev    \[bu] git

\[bu] curl          \[bu] ffmpeg                \[bu] zsh               \[bu] cmake

\[bu] htop          \[bu] mp3gain               \[bu] adb               \[bu] gettext 

\[bu] imagemagick   \[bu] nsxiv                 \[bu] clangd            \[bu] fonts-font-awesome

\[bu] xclip         \[bu] rsync                 \[bu] epiphany-browser  \[bu] vlc

\[bu] zathura
.EE

.B
.IP \n+[step]
.B Network

.nr sstep 0 1

.IP \n+[sstep]
.B Remove Interfaces

.EX
sudo rm /etc/network/interfaces
.EE

.IP \n+[sstep]
.B Edit config

.EX
managed=true
.EE

\(-> /etc/NetworkManager/NetworkManager.conf

.IP \n+[sstep]
.B Change DNS

.EX
185.228.168.168
.EE

.IP \n+[sstep]
.B Change hosts file

.EX
sudo wget "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts" -O /etc/hosts
.EE

.IP \n+[sstep]
.B Restart NetworkManager

.EX
sudo service NetworkManager restart
.EE

.B
.IP \n+[step]
.B Neovim

.nr sstep 0 1

.IP \n+[sstep]
.B Clone repository

.EX
mkdir .config/nvim
cd .config/nvim/
git clone https://github.com/neovim/neovim
.EE

.IP \n+[sstep]
.B Build & Config

.EX
cd .config/nvim/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
.EE

\(-> init.lua \(-> ~/.config/nvim/init.lua

.IP \n+[sstep]
.B Plugins

.EX
~/.config/nvim/pack/
            lspconfig/start/
                [git clone https://github.com/neovim/nvim-lspconfig]

            LuaSnip/start/
                [git clone https://github.com/L3MON4D3/LuaSnip.git]

            cmp/start/
                [git clone https://github.com/hrsh7th/cmp-buffer.git]
                [git clone https://github.com/hrsh7th/cmp-cmdline.git]
                [git clone https://github.com/hrsh7th/cmp-nvim-lsp.git]
                [git clone https://github.com/hrsh7th/cmp-path.git]
                [git clone https://github.com/hrsh7th/nvim-cmp.git]

            cmp_luasnip/start/
                [git clone https://github.com/saadparwaiz1/cmp_luasnip.git]
.B
.IP \n+[step]
.B Zsh

.nr sstep 0 1

.IP \n+[sstep]
.B Default Shell

.EX
chsh -s /usr/bin/zsh
.EE

.IP \n+[sstep]
.B Startx

.EX
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
exec startx &>/dev/null
fi
.EE

\(-> Add to .zprofile

.IP \n+[sstep]
.B Config

.EX
export GPG_TTY=$(tty)
typeset -U PATH
setopt correct
setopt numericglobsort
precmd() { print "" }
PROMPT='%B%F{15}%1d %F{246}$%f%b '
.EE

\(-> Add to .zshrc

.B
.IP \n+[step]
.B Suckless
.nr sstep 0 1

.IP \n+[sstep]
.B Clone Repository

.EX
mkdir .config/suckless
cd .config/suckless
git clone https://git.suckless.org/dmenu
git clone https://git.suckless.org/dwm
git clone https://git.suckless.org/slock
.EE

\(-> sudo make install

.IP \n+[sstep]
.B Autostart

.EX
xsetroot -solid "#070605"
exec /usr/local/bin/slstatus &
exec /usr/local/bin/dwm 2> ~/log
.EE

\(-> ~/.Xsession

.IP \n+[sstep]
.B Dwm Config

.EX
// Include special keyboard keys
#include <X11/XF86keysym.h>

// Set font
static const char *fonts[]          = { "FontAwesome:pixelsize=18:antialias=true:autohint=true" };

// Set colors
[SchemeNorm] = { "#fefefe", "#070605", "#070605" },
[SchemeSel]  = { "#070605", "#fefefe", "#fefefe" },

// Border px fix
static const int resizehints = 0;

// Change to super key
#define MODKEY Mod4Mask

// Set keys
static const char *termcmd[]  = { "xterm", "-fa", "DejaVu Sans Mono", "-fs", "10", NULL };
static const char *lockcmd[]        = { "slock", NULL };
static const char *vol_upcmd[]      = { "pactl", "set-sink-volume", "@DEFAULT_SINK@", "+10%", NULL };
static const char *vol_downcmd[]    = { "pactl", "set-sink-volume", "@DEFAULT_SINK@", "-10%", NULL };
static const char *vol_mutecmd[]    = { "pactl", "set-sink-volume", "@DEFAULT_SINK@", "toggle", NULL };
static const char *powercmd[]       = { "/home/konrad/.config/suckless/dwm/scripts/powermenu.sh", NULL };
static const char *mon_cmd[]        = { "/home/konrad/.config/suckless/dwm/scripts/monitor.sh", NULL };
static const char *bright_upcmd[]   = { "brightnessctl", "-d", "*", "-c", "backlight", "set", "+10%", NULL };
static const char *bright_downcmd[] = { "brightnessctl", "-d", "*", "-c", "backlight", "set", "10%-", NULL };

static const Key keys[] = {
	/* modifier                     key        function        argument */
    { 0,                            XF86XK_MonBrightnessDown, 	spawn,          {.v = bright_downcmd  } },
    { 0,                            XF86XK_MonBrightnessUp, 	spawn,          {.v = bright_upcmd  } },
    { 0,                            XF86XK_Sleep,               spawn,          {.v = lockcmd  } },
    { 0,                            XK_F7,                      spawn,          {.v = mon_cmd  } },
    { 0,                            XF86XK_ScreenSaver,         spawn,          {.v = lockcmd  } },
    { 0,                            XF86XK_AudioMute,           spawn,          {.v = vol_mutecmd  } },
    { 0,                            XF86XK_AudioLowerVolume,    spawn,          {.v = vol_downcmd  } },
    { 0,                            XF86XK_AudioRaiseVolume,    spawn,          {.v = vol_upcmd  } },
    { MODKEY,                       XK_Escape,                  spawn,          {.v = powercmd  } },
    { MODKEY,                       XK_Tab,                     focusmon,       {.i = -1 } },
	{ MODKEY|ShiftMask,             XK_Tab,                     focusmon,       {.i = +1 } },
	{ MODKEY|ShiftMask,             XK_comma,                   tagmon,         {.i = -1 } },
	{ MODKEY|ShiftMask,             XK_period,                  tagmon,         {.i = +1 } },
};
.EE

\(-> Use xev to recognize certain keys

.EX
void
drawbar(Monitor *m)
{
	int x, w, tw = 0;
	int boxs = drw->fonts->h / 9;
	int boxw = drw->fonts->h / 6 + 2;
	unsigned int i, occ = 0, urg = 0;
	Client *c;

	if (!m->showbar)
		return;

	/* draw status first so it can be overdrawn by tags later */
	if (m == selmon) { /* status is only drawn on selected monitor */
		drw_setscheme(drw, scheme[SchemeNorm]);
		tw = TEXTW(stext) - lrpad + 2; /* 2px right padding */
		drw_text(drw, m->ww - tw, 0, tw, bh, 0, stext, 0);
	}

	for (c = m->clients; c; c = c->next) {
		occ |= c->tags;
		if (c->isurgent)
			urg |= c->tags;
	}

   	drw_setscheme(drw, scheme[SchemeNorm]);
	drw_rect(drw, x, 0, m->ww - tw, bh, 1, 1);
    drw_map(drw, m->barwin, 0, 0, m->ww, bh);
}
.EE

\(-> dwm.c (line 738 function drawbar)

.IP \n+[sstep]

.B Statusbar

.EX
#! /bin/bash

battery() {
    status="$(cat /sys/class/power_supply/BAT0/status)"
    status1="$(cat /sys/class/power_supply/BAT1/status)"
    percent="$(cat /sys/class/power_supply/BAT0/capacity)"

    if [[ $status == "Charging" || $status1 == "Charging" ]]; then
        symbol="\uf0e7"
    fi

    if [[ $percent -gt 80 ]]; then
        symbol="\uf240"
    elif [[ $percent -gt 60 ]]; then
        symbol="\uf241"
    
    elif [[ $percent -gt 40 ]]; then
        symbol="\uf242"
    
    elif [[ $percent -gt 20 ]]; then
        symbol="\uf243"
    else
        symbol="\uf244"
    fi 

    echo -n -e $symbol
}

wifi() {
    connectivity="$(nmcli networking connectivity)"

    if [[ $connectivity == "none" || $connectivity == "unknown" ]]; then
        symbol="\uf072"
    elif [[ $connectivity == "portal" || $connectivity == "limited" ]]; then
        symbol="\uf015"
    else
        symbol="\uf1eb"
    fi

    echo -n -e $symbol
}

while true;
    do
        dateStatus=$(date +%H:%M)
        batteryStatus=$(battery)
        networkStatus=$(wifi)
        xsetroot -name "$dateStatus   $networkStatus   $batteryStatus   ";
        sleep 10;
done
.EE

\(-> ~/.config/suckless/dwm/scripts/statusbar.sh

.EX
exec /home/konrad/.config/suckless/dwm/scripts/statusbar.sh &
.EE

\(-> ~/.Xsession 

.B Power Menu

.EX
#!/bin/bash
options="\uf023\n\uf011\n\uf021"
selected=$(echo -e $options | dmenu)

if [[ $selected == "" ]]; then
    systemctl poweroff
elif [[ $selected == "" ]]; then
    systemctl reboot
elif [[ $selected == "" ]]; then
    systemctl suspend
    slock
fi
.EE

\(-> ~/.config/suckless/dwm/scripts/powermenu.sh

.EX
sudo chmod +x powermenu.sh
.EE

.IP \n+[sstep]
.B Monitor Menu

.EX
actions="left\nright\nabove\nbelow\noff\non"
display=$(xrandr | grep " primary " | awk '{print$1 }')

monitor=$(xrandr | grep " connected " | grep -v $display | awk '{ print$1 }' | dmenu -p "Monitor")
action=$(echo -e $actions | dmenu -p "Action")

if [[ $action = "left" ]]; then
    xrandr --output $monitor --auto --left-of $display
elif [[ $action = "right" ]]; then
    xrandr --output $monitor --auto --right-of $display
elif [[ $action = "above" ]]; then
    xrandr --output $monitor --auto --above $display
elif [[ $action = "below" ]]; then
    xrandr --output $monitor --auto --below $display
elif [[ $action = "off" ]]; then
    xrandr --output $monitor --off
elif [[ $action = "on" ]]; then
    xrandr --output $monitor
fi
.EE

\(-> Write in ~/config/suckless/dwm/scripts/monitor.sh

.EX
sudo chmod +x monitor.sh
.EE

.IP \n+[sstep]
.B Dmenu Config

.EX
    [SchemeOut] = { "#000000", "#00ffff" },
    [SchemeNorm] = { "#fefefe", "#070605" },
    [SchemeSel]  = { "#070605", "#fefefe" },
.EE

.B
.IP \n+[step]
.B Touchpad

.EX
Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "Tapping" "on"
EndSection
.EE

\(-> /etc/X11/xorg.conf.d/40-libinput.conf

.B
.IP \n+[step]
.B Firewall

.nr sstep 0 1

.IP \n+[sstep]
.B Enable

.EX
sudo ufw enable
.EE

.IP \n+[sstep]
.B Defaults

.EX
sudo ufw default deny incoming
sudo ufw default allow outgoing
.EE

.IP \n+[sstep]
.B Status

.EX
sudo ufw status verbose
.EE

.IP \n+[sstep]
.B Allow/Deny Programms

.EX
sudo ufw allow DNS
sudo ufw allow CUPS
.EE

.B
.IP \n+[step]
.B Python

.nr sstep 0 1

.IP \n+[sstep]
.B Install pyenv

.EX
git clone https://github.com/pyenv/pyenv.git ~/.pyenv
.EE

.IP \n+[sstep]
.B Environment

.EX
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/python@3.11/libexec/bin/python3:$PATH"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
.EE

\(-> ~/.zshrc

.IP \n+[sstep]
.B Show availible Versions

.EX
pyenv install -l
.EE

.IP \n+[sstep]
.B Install <version>

.EX
pyenv install <version>
.EE

.IP \n+[sstep]
.B Set global version

.EX
pyenv global <version>
.EE

.IP \n+[sstep]
.B Packages

\[bu] pyright

.B
.IP \n+[step]
.B Speed Improvments

.nr sstep 0 1

.IP \n+[sstep]
.B Disable Grub Screen

.EX
set GRUB_TIMEOUT=0
.EE

\(-> /etc/default/grub and run sudo update-grub2

.IP \n+[sstep]
.B Ununsed Services

.EX
systemctl disable bluetooth.service
systemctl disable NetworkManager-wait-online.service
.EE

.IP \n+[sstep]
.B Check Speed

.EX
systemd-analyze blame
systemd-analyze critical-chain
systemd-analyze plot > time.svg
.EE

.B
.IP \n+[step]
.B Tutanota Mail Client

.nr sstep 0 1

.IP \n+[sstep]
Download Client

.EX
sudo wget https://app.tuta.com/desktop/tutanota-desktop-linux.AppImage -O /usr/bin/tutanota.AppImage
sudo chmod +x /usr/bin/tutanota.AppImage
.EE

.SH Ffmpeg

.SS Watermarks removal

.EX
ffplay FILE.mp4 -vf "delogo=x=?:y=?:w=?:h=?:show=1"
.EE

.SS Crop

.EX
ffmpeg -i INPUT -filter:v "crop=<width>:<height>:<x>:<y>" <output>
.EE

.SS Split

.EX
ffmpeg -ss 00:01:00.00 -to 00:02:00.00 -i input.mp4 -c copy output.mp4
.EE

.SS Convert to libx265

.EX
ffmpeg -i <input> -c:v libx265 -crf 26 -preset fast -c:a aac -tag:v hvc1 <output>.mp4
.EE

.SS ADB Backup

.EE
.IP /storage/self/primary/Documents/
.IP /storage/self/primary/Download/
.IP /storage/self/primary/Pictures/Screenshots/
.IP /storage/self/primary/Pictures/Whatsapp/
.IP /storage/self/primary/Pictures/eBay Kleinanzeigen/
.IP /storage/self/primary/DCIM/Camera/
.IP /storage/self/primary/Android/media/com.whatsapp/WhatsApp/Media/WhatsApp Images/
.IP /storage/self/primary/Android/media/com.whatsapp/WhatsApp/Media/WhatsApp Video/
.EX
